### ISSUE TITLE
Rename crud objects to e.g. crud_welding_point instead of welding_point

### ISSUE THREAD

**Issue by janosbrodbeck** [SQE22-RoboticWelding/model-transformer-welding-backend#27]
Really annoying, since the current naming blocks the possibility to name objects e.g. `welding_points` in a function when the corresponding crud object is needed as well. Renaming the crud object should avoid this problem as it is unlikely that we have a possible name collision with the new name.

**Comment by dolevi-tub** [comment]
Solved somewhere
